apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_KEY: c2tfdGVzdF81MVBsNWFBUDUyaENsbmZyTTZWMzlJdlFnVXI1ZFNJYzlPR1NSWmlhaEhYVzZHRGRDUjhHYUlQRG5Fd0Jzb3dwWWV4UExTczBWUlp6OENBMlBiTTZnZ0V4MDAwcTNMQjhMTWo=
