apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
      

build:
  local:
    push: false
  #googleCloudBuild:
    #projectId: ticketing-dev-429810
  artifacts:
    - image: dhavalshekhada/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
     