name: tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  # Specify the branch or branches to run the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        

      - name: Setup Environment
        run: |
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
          echo "STRIPE_KEY=${{ secrets.STRIPE_KEY }}" >> .env

      - name: Install dependencies and run tests
        run: |
          cd ticketing/tickets
          npm install
          npm run test:ci
