name: test_payments

on:
  push:
    branches:
      - main  #
  pull_request:
    branches:
      - main  # Specify the branch or branches to run the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
       
      - name: Setup Environment and run tests
        env: 
          JWT_KEY : ${{ secrets.JWT_KEY }}
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        run: |
          cd ticketing/payments
          npm install
          npm run test:ci
