name: test_auth

on: 
  pull_request
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - run: 
            echo "JWT_KEY"=${{ secrets.JWT_KEY}}" >> .env
            echo "STRIPE_KEY=${{ secrets.STRIPE_KEY }}" >> .env
            cd ticketing/auth && npm install && npm run test:ci
